In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv( #DataFrame 
    r"C:\Users\Ivana\Desktop\NRW_Hotel_Demand_Analysis\data\raw\45412-15i.csv",
    sep=";",
    encoding="cp1252", # Zeichenkodierung der CSV-Datei, damit Umlaute wie ü und ö korrekt gelesen werden
    skiprows=5,  # Die ersten fünf Zeilen mit Beschreibungen und Überschriften überspringen
    header=None,  # Keine Zeile als Spaltenüberschrift verwenden
    dtype=str
)

In [3]:
df.head(10)

,0,1,2,3,4,5,6,7,8,9,10
0,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Januar,136111,"-0,1",217394,"-0,1","1,6"
1,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Februar,124469,"+2,2",190699,"+7,7","1,5"
2,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,März,46149,"-69,1",68032,"-69,4","1,5"
3,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,April,3431,"-97,3",7354,"-96,1","2,1"
4,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Mai,10572,"-92,6",16993,"-92,0","1,6"
5,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Juni,28740,"-79,1",43960,"-79,1","1,5"
6,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Juli,46356,"-66,4",71054,"-64,2","1,5"
7,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,August,59320,"-51,0",94684,"-47,9","1,6"
8,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,September,69082,"-51,0",107912,"-49,1","1,6"
9,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Oktober,49100,"-60,2",77033,"-61,1","1,6"

In [4]:
df.shape  # Anzahl der Zeilen und Spalten anzeigen

(8068, 11)

In [5]:
df.tail(10)  # Die letzten 10 Zeilen des DataFrames anzeigen

,0,1,2,3,4,5,6,7,8,9,10
8058,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Juli,73265,"-5,9",127292,"-3,3","1,7"
8059,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,August,78758,"+0,9",134091,"+0,7","1,7"
8060,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,September,89672,"+3,9",147108,"+3,7","1,6"
8061,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Oktober,95099,"+7,9",153734,"+6,7","1,6"
8062,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,November,97269,"+0,9",150895,"+1,6","1,6"
8063,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Dezember,87397,"+7,2",141384,"+9,3","1,6"
8064,__________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8065,"Zu ""gesamte Tabelle:""\nAbweichungen zu anderen...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8066,"© IT.NRW, Düsseldorf, 2026. Dieses Werk ist li...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8067,Stand: 06.10.2026 / 11:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df.iloc[:-4]  # Die letzten vier Zeilen entfernen

In [7]:
df.tail(10)

,0,1,2,3,4,5,6,7,8,9,10
8054,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,März,86378,"+20,8",139561,"+18,5","1,6"
8055,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,April,77545,"-4,4",127019,"-1,5","1,6"
8056,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Mai,86035,"+10,4",138738,"+10,0","1,6"
8057,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Juni,73944,"-21,7",122206,"-22,6","1,7"
8058,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Juli,73265,"-5,9",127292,"-3,3","1,7"
8059,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,August,78758,"+0,9",134091,"+0,7","1,7"
8060,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,September,89672,"+3,9",147108,"+3,7","1,6"
8061,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Oktober,95099,"+7,9",153734,"+6,7","1,6"
8062,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,November,97269,"+0,9",150895,"+1,6","1,6"
8063,2025,Insgesamt,05913,"Dortmund, krfr. Stadt",Insgesamt,Dezember,87397,"+7,2",141384,"+9,3","1,6"

In [8]:
df.info()  # Datentypen und Anzahl der nicht fehlenden Werte anzeigen

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8064 entries, 0 to 8063
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8064 non-null   object
 1   1       8064 non-null   object
 2   2       8064 non-null   object
 3   3       8064 non-null   object
 4   4       8064 non-null   object
 5   5       8064 non-null   object
 6   6       8064 non-null   object
 7   7       8064 non-null   object
 8   8       8064 non-null   object
 9   9       8064 non-null   object
 10  10      8064 non-null   object
dtypes: object(11)
memory usage: 693.1+ KB

In [9]:
df.isna().sum()  # Fehlende Werte pro Spalte zählen

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64

In [10]:
df.columns = [
    "year",
    "accommodation_type",
    "city_code",
    "city",
    "origin_continent",
    "month",
    "arrivals",
    "arrivals_yoy_pct", # Veränderung der Ankünfte zum Vorjahresmonat (%)
    "overnight_stays",
    "overnight_stays_yoy_pct", # Veränderung der Übernachtungen zum Vorjahresmonat (%)
    "average_stay"
]

In [11]:
df.head()

,year,accommodation_type,city_code,city,origin_continent,month,arrivals,arrivals_yoy_pct,overnight_stays,overnight_stays_yoy_pct,average_stay
0,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Januar,136111,"-0,1",217394,"-0,1","1,6"
1,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Februar,124469,"+2,2",190699,"+7,7","1,5"
2,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,März,46149,"-69,1",68032,"-69,4","1,5"
3,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,April,3431,"-97,3",7354,"-96,1","2,1"
4,2020,Hotels,05111,"Düsseldorf, krfr. Stadt",Europa,Mai,10572,"-92,6",16993,"-92,0","1,6"

In [12]:
df.duplicated().sum()  # Vollständig doppelte Zeilen zählen

np.int64(0)

In [13]:
df["accommodation_type"].value_counts()   # Vorhandene Unterkunftsarten anzeigen

accommodation_type
Hotels       4032
Insgesamt    4032
Name: count, dtype: int64

In [14]:
df = df[df["accommodation_type"] == "Hotels"] # Nur Hotels behalten

In [15]:
df["accommodation_type"].value_counts()  # Unterkunftsarten und Zeilenanzahl prüfen

accommodation_type
Hotels    4032
Name: count, dtype: int64

In [16]:
df["city"].unique()   # Vorhandene Städte anzeigen

array(['    Düsseldorf, krfr. Stadt', '    Duisburg, krfr. Stadt',
       '    Essen, krfr. Stadt', '    Aachen, krfr. Stadt',
       '    Bonn, krfr. Stadt', '    Köln, krfr. Stadt',
       '    Leverkusen, krfr. Stadt', '    Dortmund, krfr. Stadt'],
      dtype=object)

In [17]:
df["city"] = df["city"].str.strip().str.replace(", krfr. Stadt", "", regex=False)   # Leerzeichen und den Zusatz „, krfr. Stadt“ entfernen

In [18]:
df["city"].unique()

array(['Düsseldorf', 'Duisburg', 'Essen', 'Aachen', 'Bonn', 'Köln',
       'Leverkusen', 'Dortmund'], dtype=object)

In [19]:
df["year"].unique()  # Vorhandene Jahre anzeigen

array(['2020', '2021', '2022', '2023', '2024', '2025'], dtype=object)

In [20]:
df["month"].unique()  # Vorhandene Monate anzeigen

array(['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli',
       'August', 'September', 'Oktober', 'November', 'Dezember'],
      dtype=object)

In [21]:
df["origin_continent"].unique()  # Vorhandene Kontinente anzeigen

array(['Europa', 'Afrika', 'Asien', 'Amerika',
       'Australien, Neuseeland und Ozeanien',
       'Staatenlos, unbekannt, ungeklärt, ohne Angabe', 'Insgesamt'],
      dtype=object)

In [22]:
(df == "-").sum() # Anzahl der Zellen mit dem Wert "-" zählen

year                         0
accommodation_type           0
city_code                    0
city                         0
origin_continent             0
month                        0
arrivals                   634
arrivals_yoy_pct           552
overnight_stays            627
overnight_stays_yoy_pct    544
average_stay               634
dtype: int64

In [23]:
(df == ".").sum() # Anzahl der Zellen mit dem Wert "." zählen

year                       0
accommodation_type         0
city_code                  0
city                       0
origin_continent           0
month                      0
arrivals                   0
arrivals_yoy_pct           0
overnight_stays            0
overnight_stays_yoy_pct    0
average_stay               0
dtype: int64

In [24]:
(df == "/").sum() # Anzahl der Zellen mit dem Wert "/" zählen

year                       0
accommodation_type         0
city_code                  0
city                       0
origin_continent           0
month                      0
arrivals                   0
arrivals_yoy_pct           0
overnight_stays            0
overnight_stays_yoy_pct    0
average_stay               0
dtype: int64

In [25]:
df["year"] = df["year"].astype(int)  # Jahr in Ganzzahl umwandeln
df["year"].dtype

dtype('int64')

In [26]:
df["arrivals"] = df["arrivals"].replace("-", "0") 
df["arrivals_yoy_pct"] = df["arrivals_yoy_pct"].replace("-", "0")
df["overnight_stays"] = df["overnight_stays"].replace("-", "0")
df["overnight_stays_yoy_pct"] = df["overnight_stays_yoy_pct"].replace("-", "0")

# „-“ durch „0“ ersetzen

In [27]:
(df == "-").sum()

year                         0
accommodation_type           0
city_code                    0
city                         0
origin_continent             0
month                        0
arrivals                     0
arrivals_yoy_pct             0
overnight_stays              0
overnight_stays_yoy_pct      0
average_stay               634
dtype: int64

In [28]:
# Ankünfte und Übernachtungen in ganze Zahlen umwandeln
df["arrivals"] = df["arrivals"].astype(int)
df["overnight_stays"] = df["overnight_stays"].astype(int)

In [29]:
df[["arrivals", "overnight_stays"]].dtypes

arrivals           int64
overnight_stays    int64
dtype: object

In [30]:
df["average_stay"] = df["average_stay"].replace("-", float("nan"))  # „-“ durch NaN ersetzen 
# Wir setzen nicht 0 ein, denn „der Durchschnitt lässt sich nicht berechnen“ ist nicht dasselbe wie „der Durchschnitt beträgt 0 Nächte“.
# float("nan") → ein tatsächlicher NaN-Wert, der in einer numerischen Spalte verwendet werden kann.

In [31]:
# Dezimalkommas durch Punkte ersetzen
df["average_stay"] = df["average_stay"].str.replace(",", ".", regex=False)

In [32]:
df["average_stay"].dtype

dtype('O')

In [33]:
# In Dezimalzahlen umwandeln
df["average_stay"] = df["average_stay"].astype(float)

In [34]:
df["average_stay"].dtype

dtype('float64')

In [35]:
# Fehlende Werte in der Aufenthaltsdauer zählen
df["average_stay"].isna().sum()

np.int64(634)

In [36]:
df.loc[df["average_stay"].isna(),"arrivals"].value_counts()  
# Ankünfte für Zeilen mit fehlender Aufenthaltsdauer prüfen

arrivals
0    634
Name: count, dtype: int64

In [37]:
month_numbers = {
    "Januar": 1,
    "Februar": 2,
    "März": 3,
    "April": 4,
    "Mai": 5,
    "Juni":6,
    "Juli":7,
    "August": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Dezember": 12
}

In [38]:
df["month_number"] = df["month"].map(month_numbers) #Monatsnummern für die richtige Sortierung in SQL und Power BI erstellen

In [39]:
df[["month", "month_number"]].head(12)

        month  month_number
0      Januar             1
1     Februar             2
2        März             3
3       April             4
4         Mai             5
5        Juni             6
6        Juli             7
7      August             8
8   September             9
9     Oktober            10
10   November            11
11   Dezember            12

In [40]:
df["date"] = pd.to_datetime({
    "year" : df["year"],
    "month" : df["month_number"],
    "day" : 1
})

# Monatsdatum für Zeitreihen in SQL und Power BI erstellen

In [41]:
df[["year", "month_number", "date"]].head()

   year  month_number       date
0  2020             1 2020-01-01
1  2020             2 2020-02-01
2  2020             3 2020-03-01
3  2020             4 2020-04-01
4  2020             5 2020-05-01

In [42]:
df["date"].dtype

dtype('<M8[ns]')

In [43]:
df["date"].isna().sum()

np.int64(0)

In [44]:
df.dtypes

year                                int64
accommodation_type                 object
city_code                          object
city                               object
origin_continent                   object
month                              object
arrivals                            int64
arrivals_yoy_pct                   object
overnight_stays                     int64
overnight_stays_yoy_pct            object
average_stay                      float64
month_number                        int64
date                       datetime64[ns]
dtype: object

In [45]:
df["arrivals_yoy_pct"] = df["arrivals_yoy_pct"].replace("x", float("nan"))  # „x“ durch NaN ersetzen

In [46]:
df["overnight_stays_yoy_pct"] = df["overnight_stays_yoy_pct"].replace("x", float("nan"))  # „x“ durch NaN ersetzen

In [47]:
df["arrivals_yoy_pct"] = df["arrivals_yoy_pct"].str.replace(",", ".").astype(float)
df["overnight_stays_yoy_pct"] = df["overnight_stays_yoy_pct"].str.replace(",", ".").astype(float)

In [48]:
df[["arrivals_yoy_pct", "overnight_stays_yoy_pct"]].dtypes

arrivals_yoy_pct           float64
overnight_stays_yoy_pct    float64
dtype: object

In [49]:
df.dtypes

year                                int64
accommodation_type                 object
city_code                          object
city                               object
origin_continent                   object
month                              object
arrivals                            int64
arrivals_yoy_pct                  float64
overnight_stays                     int64
overnight_stays_yoy_pct           float64
average_stay                      float64
month_number                        int64
date                       datetime64[ns]
dtype: object

In [50]:
df.isna().sum()  # Fehlende Werte pro Spalte zählen

year                         0
accommodation_type           0
city_code                    0
city                         0
origin_continent             0
month                        0
arrivals                     0
arrivals_yoy_pct            93
overnight_stays              0
overnight_stays_yoy_pct     87
average_stay               634
month_number                 0
date                         0
dtype: int64

In [51]:
# Anzahl der Zeilen und Spalten prüfen
df.shape

(4032, 13)

In [52]:
# Bereinigte Daten als CSV-Datei speichern
output_path = r"C:\Users\Ivana\Desktop\NRW_Hotel_Demand_Analysis\data\clean\clean_nrw_hotels.csv"

df.to_csv(output_path, index=False, sep=";", encoding="utf-8-sig")  # Bereinigte Daten als CSV-Datei speichern

 #encoding="utf-8-sig" Kodierung für die korrekte Darstellung von Sonderzeichen wie ü, ö und č

In [53]:
df[["month", "arrivals_yoy_pct", "overnight_stays_yoy_pct"]].head(12)

        month  arrivals_yoy_pct  overnight_stays_yoy_pct
0      Januar              -0.1                     -0.1
1     Februar               2.2                      7.7
2        März             -69.1                    -69.4
3       April             -97.3                    -96.1
4         Mai             -92.6                    -92.0
5        Juni             -79.1                    -79.1
6        Juli             -66.4                    -64.2
7      August             -51.0                    -47.9
8   September             -51.0                    -49.1
9     Oktober             -60.2                    -61.1
10   November             -87.5                    -86.5
11   Dezember             -90.1                    -89.0