In [ ]:
import pandas as pd

In [2]:
df_aachen = pd.read_csv( 
    r"C:\Users\Ivana\Desktop\NRW_Hotel_Demand_Analysis\data\raw\aachen_raw.csv",
    sep=";",
    encoding="cp1252", 
    skiprows=5,  
    header=None,  
    dtype=str
)

In [3]:
df_aachen.head(10)

,0,1,2,3,4,5,6,7,8,9,10
0,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Januar,17372,"-5,8",25505,"-8,6","1,5"
1,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Februar,17784,"+1,2",26539,"+3,2","1,5"
2,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,März,7507,"-65,1",11543,"-65,5","1,5"
3,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,April,1327,"-94,1",2626,"-92,7","2,0"
4,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Mai,3853,"-84,9",6766,"-83,0","1,8"
5,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Juni,8884,"-64,2",14249,"-63,8","1,6"
6,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Juli,14503,"-43,8",23844,"-43,8","1,6"
7,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,August,18457,"-29,2",31412,"-27,6","1,7"
8,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,September,15998,"-38,8",25438,"-36,7","1,6"
9,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Oktober,11931,"-51,6",20526,"-46,6","1,7"

In [5]:
df_aachen.tail(6)

,0,1,2,3,4,5,6,7,8,9,10
1006,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,November,52515,"+2,3",91657,"-1,4","1,7"
1007,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,Dezember,62964,"+12,2",109671,"+7,5","1,7"
1008,__________,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,"Zu ""gesamte Tabelle:""\nAbweichungen zu anderen...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1010,"© IT.NRW, Düsseldorf, 2026. Dieses Werk ist li...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1011,Stand: 13.10.2026 / 14:08:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_aachen = df_aachen.iloc[:-4]

In [7]:
df_aachen.tail(6)

,0,1,2,3,4,5,6,7,8,9,10
1002,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,Juli,56657,"+10,5",111712,"+8,0","2,0"
1003,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,August,56796,"+4,9",107963,"+4,3","1,9"
1004,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,September,54550,"+12,4",102408,"+10,0","1,9"
1005,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,Oktober,54676,"+8,6",101209,"+2,3","1,9"
1006,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,November,52515,"+2,3",91657,"-1,4","1,7"
1007,2025,Insgesamt,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Insgesamt,Dezember,62964,"+12,2",109671,"+7,5","1,7"

In [8]:
df_aachen.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
dtype: int64

In [9]:
df_aachen.columns = [
    "year",
    "accommodation_type",
    "city_code",
    "city",
    "origin_continent",
    "month",
    "arrivals",
    "arrivals_yoy_pct", # Veränderung der Ankünfte zum Vorjahresmonat (%)
    "overnight_stays",
    "overnight_stays_yoy_pct", # Veränderung der Übernachtungen zum Vorjahresmonat (%)
    "average_stay"
]

In [10]:
df_aachen.head(10)

,year,accommodation_type,city_code,city,origin_continent,month,arrivals,arrivals_yoy_pct,overnight_stays,overnight_stays_yoy_pct,average_stay
0,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Januar,17372,"-5,8",25505,"-8,6","1,5"
1,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Februar,17784,"+1,2",26539,"+3,2","1,5"
2,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,März,7507,"-65,1",11543,"-65,5","1,5"
3,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,April,1327,"-94,1",2626,"-92,7","2,0"
4,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Mai,3853,"-84,9",6766,"-83,0","1,8"
5,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Juni,8884,"-64,2",14249,"-63,8","1,6"
6,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Juli,14503,"-43,8",23844,"-43,8","1,6"
7,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,August,18457,"-29,2",31412,"-27,6","1,7"
8,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,September,15998,"-38,8",25438,"-36,7","1,6"
9,2020,Hotels,05334002,"Aachen, krfr. Stadt (ab 21.10.2009)",Europa,Oktober,11931,"-51,6",20526,"-46,6","1,7"

In [11]:
df_aachen.duplicated().sum()

np.int64(0)

In [12]:
df_aachen["accommodation_type"].value_counts()

accommodation_type
Hotels       504
Insgesamt    504
Name: count, dtype: int64

In [13]:
df_aachen = df_aachen[df_aachen["accommodation_type"] == "Hotels"]

In [15]:
df_aachen["accommodation_type"].value_counts()

accommodation_type
Hotels    504
Name: count, dtype: int64

In [16]:
df_aachen['city'].unique()

array(['      Aachen, krfr. Stadt (ab 21.10.2009)'], dtype=object)

In [17]:
df_aachen['city'] = df_aachen['city'].str.replace(", krfr. Stadt", "", regex=False)

In [18]:
df_aachen['city'].unique()

array(['      Aachen (ab 21.10.2009)'], dtype=object)

In [19]:
df_aachen['city'] = df_aachen['city'].str.replace('(ab 21.10.2009)', '', regex=False).str.strip()

In [20]:
df_aachen['city'].unique()

array(['Aachen'], dtype=object)

In [22]:
df_aachen["year"].unique()

array(['2020', '2021', '2022', '2023', '2024', '2025'], dtype=object)

In [23]:
df_aachen["month"].unique()

array(['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli',
       'August', 'September', 'Oktober', 'November', 'Dezember'],
      dtype=object)

In [25]:
df_aachen["origin_continent"].unique()

array(['Europa', 'Afrika', 'Asien', 'Amerika',
       'Australien, Neuseeland und Ozeanien',
       'Staatenlos, unbekannt, ungeklärt, ohne Angabe', 'Insgesamt'],
      dtype=object)

In [26]:
(df_aachen == "-").sum()

year                        0
accommodation_type          0
city_code                   0
city                        0
origin_continent            0
month                       0
arrivals                   14
arrivals_yoy_pct            2
overnight_stays            14
overnight_stays_yoy_pct     2
average_stay               14
dtype: int64

In [27]:
(df_aachen == "/").sum()

year                       0
accommodation_type         0
city_code                  0
city                       0
origin_continent           0
month                      0
arrivals                   0
arrivals_yoy_pct           0
overnight_stays            0
overnight_stays_yoy_pct    0
average_stay               0
dtype: int64

In [28]:
(df_aachen == "x").sum()

year                        0
accommodation_type          0
city_code                   0
city                        0
origin_continent            0
month                       0
arrivals                    0
arrivals_yoy_pct           13
overnight_stays             0
overnight_stays_yoy_pct    13
average_stay                0
dtype: int64

In [29]:
(df_aachen == ".").sum()

year                       0
accommodation_type         0
city_code                  0
city                       0
origin_continent           0
month                      0
arrivals                   0
arrivals_yoy_pct           0
overnight_stays            0
overnight_stays_yoy_pct    0
average_stay               0
dtype: int64

In [30]:
df_aachen['arrivals'] = df_aachen['arrivals'].replace("-", "0")
df_aachen['arrivals_yoy_pct'] = df_aachen['arrivals_yoy_pct'].replace("-", "0")
df_aachen['overnight_stays'] = df_aachen['overnight_stays'].replace("-", "0")
df_aachen['overnight_stays_yoy_pct'] = df_aachen['overnight_stays_yoy_pct'].replace("-", "0")
df_aachen['average_stay'] = df_aachen['average_stay'].replace("-", float("nan"))
df_aachen['arrivals_yoy_pct'] = df_aachen['arrivals_yoy_pct'].replace("x", float("nan"))
df_aachen['overnight_stays_yoy_pct'] = df_aachen['overnight_stays_yoy_pct'].replace("x", float("nan"))

In [31]:
df_aachen.isna().sum()

year                        0
accommodation_type          0
city_code                   0
city                        0
origin_continent            0
month                       0
arrivals                    0
arrivals_yoy_pct           13
overnight_stays             0
overnight_stays_yoy_pct    13
average_stay               14
dtype: int64

In [32]:
df_aachen["year"] = df_aachen["year"].astype(int)
df_aachen["arrivals"] = df_aachen["arrivals"].astype(int)
df_aachen["overnight_stays"] = df_aachen["overnight_stays"].astype(int)

In [33]:
df_aachen.dtypes

year                        int64
accommodation_type         object
city_code                  object
city                       object
origin_continent           object
month                      object
arrivals                    int64
arrivals_yoy_pct           object
overnight_stays             int64
overnight_stays_yoy_pct    object
average_stay               object
dtype: object

In [34]:
df_aachen["arrivals_yoy_pct"] = df_aachen["arrivals_yoy_pct"].replace(",", ".", regex=True).astype(float)
df_aachen["overnight_stays_yoy_pct"] = df_aachen["overnight_stays_yoy_pct"].replace(",", ".", regex=True).astype(float)
df_aachen["average_stay"] = df_aachen["average_stay"].replace(",", ".", regex=True).astype(float)

In [35]:
df_aachen.dtypes

year                         int64
accommodation_type          object
city_code                   object
city                        object
origin_continent            object
month                       object
arrivals                     int64
arrivals_yoy_pct           float64
overnight_stays              int64
overnight_stays_yoy_pct    float64
average_stay               float64
dtype: object

In [36]:
month_numbers = {
    "Januar": 1,
    "Februar": 2,
    "März": 3,
    "April": 4,
    "Mai": 5,
    "Juni":6,
    "Juli":7,
    "August": 8,
    "September": 9,
    "Oktober": 10,
    "November": 11,
    "Dezember": 12
}

In [37]:
df_aachen["month_number"] = df_aachen["month"].map(month_numbers)

In [40]:
df_aachen[["month","month_number"]].head(12)

        month  month_number
0      Januar             1
1     Februar             2
2        März             3
3       April             4
4         Mai             5
5        Juni             6
6        Juli             7
7      August             8
8   September             9
9     Oktober            10
10   November            11
11   Dezember            12

In [42]:
df_aachen["date"] = pd.to_datetime({
    "year" : df_aachen["year"],
    "month" : df_aachen["month_number"],
    "day" : 1
})

In [43]:
df_aachen[["year", "month", "date"]].head(10)

   year      month       date
0  2020     Januar 2020-01-01
1  2020    Februar 2020-02-01
2  2020       März 2020-03-01
3  2020      April 2020-04-01
4  2020        Mai 2020-05-01
5  2020       Juni 2020-06-01
6  2020       Juli 2020-07-01
7  2020     August 2020-08-01
8  2020  September 2020-09-01
9  2020    Oktober 2020-10-01

In [44]:
df_aachen.dtypes

year                                int64
accommodation_type                 object
city_code                          object
city                               object
origin_continent                   object
month                              object
arrivals                            int64
arrivals_yoy_pct                  float64
overnight_stays                     int64
overnight_stays_yoy_pct           float64
average_stay                      float64
month_number                        int64
date                       datetime64[ns]
dtype: object

In [45]:
df_aachen.head(10)

,year,accommodation_type,city_code,city,origin_continent,month,arrivals,arrivals_yoy_pct,overnight_stays,overnight_stays_yoy_pct,average_stay,month_number,date
0,2020,Hotels,05334002,Aachen,Europa,Januar,17372,-5.8,25505,-8.6,1.5,1,2020-01-01
1,2020,Hotels,05334002,Aachen,Europa,Februar,17784,1.2,26539,3.2,1.5,2,2020-02-01
2,2020,Hotels,05334002,Aachen,Europa,März,7507,-65.1,11543,-65.5,1.5,3,2020-03-01
3,2020,Hotels,05334002,Aachen,Europa,April,1327,-94.1,2626,-92.7,2.0,4,2020-04-01
4,2020,Hotels,05334002,Aachen,Europa,Mai,3853,-84.9,6766,-83.0,1.8,5,2020-05-01
5,2020,Hotels,05334002,Aachen,Europa,Juni,8884,-64.2,14249,-63.8,1.6,6,2020-06-01
6,2020,Hotels,05334002,Aachen,Europa,Juli,14503,-43.8,23844,-43.8,1.6,7,2020-07-01
7,2020,Hotels,05334002,Aachen,Europa,August,18457,-29.2,31412,-27.6,1.7,8,2020-08-01
8,2020,Hotels,05334002,Aachen,Europa,September,15998,-38.8,25438,-36.7,1.6,9,2020-09-01
9,2020,Hotels,05334002,Aachen,Europa,Oktober,11931,-51.6,20526,-46.6,1.7,10,2020-10-01

In [46]:
path = r"C:\Users\Ivana\Desktop\NRW_Hotel_Demand_Analysis\data\clean\aachen_clean.csv"

df_aachen.to_csv(path, index = False, encoding="utf-8-sig")

In [ ]:
# Bereinigte Daten aller Städte einlesen
df_all = pd.read_csv(
    r"C:\Users\Ivana\Desktop\NRW_Hotel_Demand_Analysis\data\clean\clean_nrw_hotels.csv",
    encoding="utf-8-sig",
    dtype={"city_code": str},  # Stadtcodes als Text mit führenden Nullen einlesen
    parse_dates=["date"],      # Datumsspalte als Datum einlesen
    sep=";"                    # Spalten durch Semikolon trennen
)

In [58]:
df_without_aachen = df_all[df_all["city_code"] != "05313"]

In [59]:
df_without_aachen.shape

(3528, 13)

In [60]:
df_corrected = pd.concat([df_without_aachen, df_aachen], ignore_index=True)

In [62]:
df_corrected.shape

(4032, 13)

In [65]:
df_corrected.to_csv(
    r"C:\Users\Ivana\Desktop\NRW_Hotel_Demand_Analysis\data\clean\clean_nrw_hotels.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)